# Generated by Django 4.1.1 on 2022-10-03 06:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCustom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('account_created', models.DateTimeField(default=datetime.datetime(2022, 10, 3, 6, 26, 56, 365939, tzinfo=datetime.timezone.utc))),
                ('account_updated', models.DateTimeField(default=datetime.datetime(2022, 10, 3, 6, 26, 56, 366045, tzinfo=datetime.timezone.utc))),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
