# Generated by Django 4.1.1 on 2022-10-20 06:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountcustom_account_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcustom',
            name='account_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 6, 28, 39, 459376, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountcustom',
            name='account_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 6, 28, 39, 459489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountcustom',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d583275-a9c1-4fbc-ac75-52e3f5c873c9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
