# Generated by Django 4.1.1 on 2022-10-21 00:47

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountcustom_account_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcustom',
            name='account_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 0, 47, 18, 438131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountcustom',
            name='account_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 0, 47, 18, 438238, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountcustom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
