# Generated by Django 4.1.1 on 2022-10-25 03:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountcustom_account_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCustom',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 10, 25, 3, 2, 42, 271676, tzinfo=datetime.timezone.utc))),
                ('user_id', models.CharField(max_length=36)),
                ('s3_bucket_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='accountcustom',
            name='account_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 3, 2, 42, 271424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountcustom',
            name='account_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 3, 2, 42, 271543, tzinfo=datetime.timezone.utc)),
        ),
    ]
